name: Build and Deploy Wyandotte Robotics Site

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Build the Docker Image
      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t wyandotte-robotics .
          echo "Docker image built successfully!"

      # Step 3: Stop and Remove Existing Container
      - name: Stop and Remove Existing Container
        run: |
          echo "Stopping and removing existing container..."
          if [ "$(docker ps -q -f name=wyandotte-robotics)" ]; then
            echo "Stopping container..."
            docker stop wyandotte-robotics
          fi
          if [ "$(docker ps -aq -f name=wyandotte-robotics)" ]; then
            echo "Removing container..."
            docker rm wyandotte-robotics
          fi
          echo "Existing container stopped and removed!"

      # Step 4: Run New Container with Health Check and Restart Policy
      - name: Run New Container with Health Check
        run: |
          echo "Running new container..."
          docker run -d \
            -p 4321:4321 \
            --name wyandotte-robotics \
            --restart unless-stopped \
            --health-cmd="curl -f http://localhost:4321/ || exit 1" \
            --health-interval=30s \
            --health-timeout=10s \
            --health-retries=3 \
            wyandotte-robotics
          echo "New container started successfully!"

      # Step 5: Clean Up Old Docker Images
      - name: Remove Unused Docker Images
        run: |
          echo "Cleaning up unused Docker images..."
          docker image prune -f
          echo "Unused Docker images removed!"
