name: Build and Deploy Wyandotte Robotics Site

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Build the Docker Image
      - name: Build Docker Image
        run: docker build -t wyandotte-robotics .

      # Step 3: Stop and Remove Existing Container (Robust Cleanup)
      - name: Stop and Remove Existing Container
        run: |
          if [ "$(docker ps -aq -f name=wyandotte-robotics)" ]; then
            docker stop wyandotte-robotics || true
            docker rm wyandotte-robotics || true
          fi

      # Step 4: Run New Container with Health Check and Restart Policy
      - name: Run New Container with Health Check
        run: |
          docker run -d \
            -p 4321:4321 \
            --name wyandotte-robotics \
            --restart unless-stopped \
            --health-cmd="curl -f http://localhost:4321/ || exit 1" \
            --health-interval=30s \
            --health-timeout=10s \
            --health-retries=3 \
            wyandotte-robotics

      # Step 5: Clean Up Old Docker Images
      - name: Remove Unused Docker Images
        run: docker image prune -f
