name: Build and Deploy Wyandotte Robotics Site

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Restore Astro Build Cache
      - name: Restore Astro Build Cache
        uses: actions/cache@v3
        with:
          path: .astro-cache
          key: astro-cache-${{ github.sha }}
          restore-keys: |
            astro-cache-

    #   - name: Move Restored Cache
    #     run: mv .astro-cache .astro/cache

      # Step 3: Build the Docker Image
      - name: Build Docker Image with Cache Volume
        run: |
          echo "Building Docker image with mounted cache..."
          docker build --build-arg CACHE_DIR=/app/.astro/cache -t wyandotte-robotics .

      # Step 4: Extract .astro/cache
      - name: Extract Astro Cache
        run: |
          echo "Extracting .astro/cache from the Docker container..."
          docker create --name wyandotte-build wyandotte-robotics
          docker cp wyandotte-build:/app/.astro/cache .astro-cache
          docker rm wyandotte-build
          echo "Astro cache extracted successfully!"

      # Step 5: Cache the Astro Build Cache
      - name: Cache Astro Build Cache
        uses: actions/cache@v3
        with:
         path: .astro-cache
         key: astro-cache-${{ github.sha }}
         restore-keys: |
              astro-cache-

      # Step 6: Stop and Remove Existing Container
      - name: Stop and Remove Existing Container
        run: |
          echo "Stopping and removing existing container..."
          if [ "$(docker ps -q -f name=wyandotte-robotics)" ]; then
            echo "Stopping container..."
            docker stop wyandotte-robotics
          fi
          if [ "$(docker ps -aq -f name=wyandotte-robotics)" ]; then
            echo "Removing container..."
            docker rm wyandotte-robotics
          fi
          echo "Existing container stopped and removed!"

      # Step 7: Run New Container with Health Check
      - name: Run New Container with Health Check
        run: |
          echo "Running new container..."
          docker run -d \
            -p 4321:4321 \
            --name wyandotte-robotics \
            --restart unless-stopped \
            --health-cmd="curl -f http://localhost:4321/ || exit 1" \
            --health-interval=30s \
            --health-timeout=10s \
            --health-retries=3 \
            wyandotte-robotics
          echo "New container started successfully!"

      # Step 8: Clean Up Old Docker Images
      - name: Remove Unused Docker Images
        run: |
          echo "Cleaning up unused Docker images..."
          docker image prune -f
          echo "Unused Docker images removed!"