name: Build & Deploy Wyandotte Robotics (Compose)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    # --------------------------------------------------------
    # 1) Checkout & restore Astro cache (UNCHANGED)
    # --------------------------------------------------------
    - name: Checkout
      uses: actions/checkout@v4

    - name: Ensure astro-cache directory
      run: mkdir -p .astro-cache

    - name: Restore Astro Build Cache
      uses: actions/cache@v3
      with:
        path: .astro-cache
        key: astro-cache-${{ hashFiles('src/content/**') }}
        restore-keys: |
          astro-cache-${{ hashFiles('src/content/**') }}

    # --------------------------------------------------------
    # 2) Build + deploy entire stack with Compose  (★ NEW ★)
    # --------------------------------------------------------
    - name: Build & Up via Compose
      run: |
        # pull latest imgproxy, build site image, recreate stack
        docker compose -f docker-compose.yml pull imgproxy
        docker compose -f docker-compose.yml up -d --build --force-recreate --remove-orphans

    # --------------------------------------------------------
    # 3) Verify health (optional)
    # --------------------------------------------------------
    - name: Check site health
      run: |
        # wait a few seconds for containers to report healthy
        sleep 10
        curl -f http://localhost:4321/ || (echo "Site not responding!" && exit 1)

    # --------------------------------------------------------
    # 4) Clean up dangling images (optional)
    # --------------------------------------------------------
    - name: Docker image prune
      run: docker image prune -f